language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - mkdir -p build/logs
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
